apiVersion: v1
kind: Secret
metadata:
  name: insurance-rag-secret
type: Opaque
stringData:
  AZURE_OPENAI_API_KEY: "YOUR_AZURE_OPENAI_API_KEY"
  AZURE_OPENAI_ENDPOINT: "https://your-resource.openai.azure.com"
  AZURE_OPENAI_API_VERSION: "2024-02-15-preview"

  CHAT_MODEL: "gpt-4o"
  EMBED_MODEL: "text-embedding-3-small"

  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  AWS_REGION: "ap-south-1"

  S3_BUCKET: "your-bucket-name"

  CHROMA_DB_DIR: "./data/chromadb"

  TENANT_ID: "star-health"